seed: 42
cuda: False
cuda_deterministic: True
capture_video: False
video_length: 1000
video_name: "eval_video"
plot_racing_line: True
max_step: 
track_cones_path: "mujoco_tracks/random_track.csv"
num_laps: 2

eval_tracks: [0, 1, 2, 3, 4]   # which track indices to evaluate on
n_episodes_per_track: 2         # episodes per track

visualize: True

env:
  num_checkpoints: 20
  lap_completion_reward: 1000
  max_env_step: 3000
  # checkpoint_bonus_step: 300
  stuck_patience: 300
  track_idx: 0
  domain_randomization: False
  waypoint_mode: "none"

ppo:
  # model_dir: "good_model/MujocoFormulaStudent__smooth_reward_steer_vel__2026-03-10_17-14-42"
  # model_dir: "good_model/MujocoFormulaStudent__faster_speed_reverse_penalty__2026-03-11_16-06-12"
  # model_dir: "models/MujocoFormulaStudent__random_map_penalty_squared__2026-03-16_17-15-36"
  # model_dir: "models/MujocoFormulaStudent__random_map__2026-03-16_17-06-50"
  # model_dir: "models/MujocoFormulaStudent__half_throttle_gear_400__2026-03-19_03-45-41"
  # model_dir: "models/MujocoFormulaStudent__responsive_steer_gear_400_relative__2026-03-19_14-13-46"

  # model_dir: "models/MujocoFormulaStudent__responsive_steer_gear_400_relative__2026-03-19_14-13-46"
  # model_dir: "models/MujocoFormulaStudent__new_reward_func_new_termination_logic__2026-03-23_03-39-10"
  # model_dir: "models/MujocoFormulaStudent__new_reward_func_new_termination_logic__2026-03-23_03-40-26"
  model_dir: "models/MujocoFormulaStudent__no_waypoint__2026-04-10_21-02-21"
  