seed: 42
cuda: False
cuda_deterministic: True
exp_name: one_checkpoint
track_exp: True
capture_video: False

env:
  num_envs: 8 # Number of drones for training
  num_checkpoints: 1
  lap_completion_reward: 50
  max_env_step: 1500
  checkpoint_bonus_step: 1500
  next_n_checkpoint: 1


wandb:
  project: mujoco-racing
  mode: offline # online
  
ppo:
  total_timesteps: 1_500_000
  batchsize: 256
  n_steps: 2048