seed: 42
cuda: True
cuda_deterministic: True
exp_name: testing
track_exp: True
capture_video: False

env:
  num_envs: 8 # Number of envs for training
  num_checkpoints: 10
  lap_completion_reward: 1000
  max_env_step: 500
  checkpoint_bonus_step: 150
  max_throttle: 1.0
  vel_penalty_weight: 0.5 # Weight for velocity penalty in the reward function
  steer_penalty_weight: 0.5 # Weight for steering penalty in the reward function
  domain_randomization: False # Whether to apply domain randomization during training

wandb:
  project: mujoco-racing-new
  mode: offline # online
  
ppo:
  total_timesteps: 1_000_000
  batchsize: 256
  n_steps: 2048